# Generated by Django 4.2.27 on 2025-12-23 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=100)),
                ('fono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('ciudad', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('alumno_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='api.alumnos')),
                ('curso_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='api.curso')),
                ('sucursal_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='api.sucursal')),
            ],
        ),
    ]
